/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package marais.vibin

import uk.co.caprica.vlcj.factory.MediaPlayerFactory
import uk.co.caprica.vlcj.player.base.MediaPlayer
import uk.co.caprica.vlcj.player.base.MediaPlayerEventAdapter
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent
import uk.co.caprica.vlcj.player.component.InputEvents
import uk.co.caprica.vlcj.player.embedded.fullscreen.unsupported.UnsupportedFullScreenStrategy
import java.awt.*
import java.awt.event.MouseEvent
import java.awt.event.MouseWheelEvent
import java.util.concurrent.locks.ReentrantLock
import javax.swing.event.MouseInputAdapter
import kotlin.concurrent.withLock
import kotlin.system.exitProcess

fun main(args: Array<String>) {

    if (args.isEmpty()) {
        println("Expected 1 argument : <mrl>")
        exitProcess(-1)
    }
    val video = args[0]

    val frame = Frame("Vibin")
    frame.isResizable = false
    frame.isUndecorated = true
    frame.isAlwaysOnTop = true
    frame.size = Dimension(128, 128)
    frame.layout = BorderLayout()

    val factory = MediaPlayerFactory()
    val playerComponent = EmbeddedMediaPlayerComponent(factory, null, UnsupportedFullScreenStrategy(), InputEvents.DISABLE_NATIVE, null)
    val player = playerComponent.mediaPlayer()
    player.audio().setVolume(80)
    player.video().setScale(0.5f)
    //playerComponent.minimumSize = Dimension(360, 360)

    val lock = ReentrantLock()
    val lockCondition = lock.newCondition()

    frame.add(playerComponent, BorderLayout.CENTER)
    val listener = object : MouseInputAdapter() {
        var location: Point? = null
        var pressed: MouseEvent? = null

        override fun mouseClicked(e: MouseEvent) {
            if (e.button == MouseEvent.BUTTON2) {
                lock.withLock { lockCondition.signalAll() }
            }
        }

        override fun mousePressed(e: MouseEvent) {
            pressed = e
        }

        override fun mouseDragged(e: MouseEvent) {
            val component: Component = frame
            location = component.getLocation(location)
            val x: Int = location!!.x - pressed!!.x + e.x
            val y: Int = location!!.y - pressed!!.y + e.y
            component.setLocation(x, y)
        }

        override fun mouseWheelMoved(e: MouseWheelEvent) {
            player.submit {
                player.audio().setVolume(player.audio().volume() - e.wheelRotation * 5)
            }
        }
    }
    playerComponent.videoSurfaceComponent().addMouseListener(listener)
    playerComponent.videoSurfaceComponent().addMouseMotionListener(listener)
    playerComponent.videoSurfaceComponent().addMouseWheelListener(listener)
    frame.isVisible = true
    frame.requestFocus()

    player.events().addMediaPlayerEventListener(object : MediaPlayerEventAdapter() {
        override fun finished(mediaPlayer: MediaPlayer?) {
            player.submit {
                player.media().start(video)
            }
        }
    })

    player.media().start(video)

    // Wait for window close event
    lock.withLock { lockCondition.await() }

    player.controls().stop()
    playerComponent.release()
    factory.release()
    frame.dispose()
}
