[package]
name = "vibin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19"
egui = "0.19"
image = { version = "0.24", default-features = false, features = ["gif"] }
kira = { version = "0.7", default-features = false, features = ["cpal", "mp3", "ogg"] }

[features]
default = ["bundle-gif-cat"]
# Bundle the cat gif
bundle-gif-cat = []
# Bundle an audio file at compile time
bundle-audio = []

[profile.dev.package.gif]
opt-level = 2
[profile.dev.package.symphonia-bundle-mp3]
opt-level = 2

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
