[package]
name = "vibin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18"
egui = "0.18"
image = { version = "0.24", default-features = false, features = ["gif"] }
cpal = "0.13"
